# Puerto de escucha y permitir conexiones desde cualquier IP (0.0.0.0)
listener 1883 0.0.0.0
max_keepalive 60

# Seguridad: No permitir conexiones sin usuario/password
allow_anonymous false
password_file /mosquitto/config/password.txt

# Persistencia de datos
persistence true
persistence_location /mosquitto/data/

# Logs para depuración (útil para ver si alguien intenta entrar)
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout